name: Publish API reference

on:
  push:
    tags:
    - '*'

env:
  DOC_ARCH: Yorkie.doccarchive
  DOC_ARCH_ZIP: $DOC_ARCH.zip

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Generate API reference doc
      run: |
        swift package --allow-writing-to-directory $DOC_ARCH \
            generate-documentation --target Yorkie \
            --output-path $DOC_ARCH
        zip -r $DOC_ARCH_ZIP $DOC_ARCH
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: $DOC_ARCH_ZIP
