name: Publish API reference

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Generate API reference doc
      run: |
        swift package --allow-writing-to-directory ../docs-temp \
            generate-documentation --target Yorkie \
            --disable-indexing \
            --output-path ../docs-temp  \
            --transform-for-static-hosting \
            --hosting-base-path hyeongsik-won/playground
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Publish API reference doc
      run: |
        rm -rf docs
        mv ../docs-temp docs
        git add docs
        git commit -m "Updates for version $GITHUB_REF_NAME"
        git push
