name: Publish API reference

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Generate API reference doc
      run: |
        swift package --allow-writing-to-directory doc-temp \
            generate-documentation --target Yorkie \
            --disable-indexing \
            --output-path doc-temp  \
            --transform-for-static-hosting \
            --hosting-base-path hyeongsik-won/playground
