name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: SwiftLint
      run: swiftlint lint --strict
    - name: SwiftFormat
      run: swiftformat --lint .
    - name: Build
      run: swift build -v
    - uses: docker-practice/actions-setup-docker@master
    - run: docker-compose -f docker/docker-compose-ci.yml up --build -d
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/YorkiePackageTests.xctest/Contents/MacOS/YorkiePackageTests -instr-profile .build/debug/codecov/default.profdata > lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: lcov.info